"""Generate docs/CLI_COVERAGE.md from the CLI catalog, risk policy, and typed-tool mapping."""

from __future__ import annotations

from pathlib import Path

from obsidian_mcp.adapters.cli import catalog
from obsidian_mcp.policy import CLI_RISK, CONFIRM_RISKS

TYPED = {
    "search:context": "native_search", "base:query": "query_base", "base:create": "create_base_item",
    "commands": "list_commands", "command": "run_command", "diff": "file_history", "history:read": "file_history",
    "sync:read": "file_history", "history:restore": "restore_file_version", "sync:restore": "restore_file_version",
    "workspace": "workspace", "tabs": "workspace", "recents": "workspace", "workspaces": "workspace",
    "workspace:save": "workspace", "workspace:load": "workspace", "workspace:delete": "workspace",
    "open": "open_in_obsidian", "sync:status": "sync_status", "sync:deleted": "sync_status",
    "publish:site": "publish_status", "publish:list": "publish_status", "publish:status": "publish_status",
    "publish:add": "publish_files", "publish:remove": "publish_files", "move": "move_file (adapter=cli)",
    "eval": "dataview_query (Dataview only)",
}
LOCAL = {
    "files": "list_files", "folders": "list_files", "file": "file_info", "folder": "file_info", "read": "read_note",
    "create": "write_note", "append": "append_note", "prepend": "prepend_note", "rename": "rename_file",
    "delete": "trash_file / delete_permanently", "backlinks": "backlinks", "links": "outgoing_links",
    "unresolved": "link_report", "orphans": "link_report", "deadends": "link_report", "outline": "outline",
    "aliases": "note_metadata", "properties": "list_properties", "property:set": "set_properties",
    "property:remove": "set_properties", "property:read": "note_metadata", "search": "search_notes",
    "tags": "list_tags", "tag": "search_notes (tag:)", "tasks": "list_tasks", "task": "set_task_status",
    "templates": "list_templates", "template:read": "render_template", "template:insert": "create_from_template",
    "daily": "daily_note", "daily:path": "daily_note", "daily:read": "daily_note", "daily:append": "append_note",
    "daily:prepend": "prepend_note", "unique": "unique_note", "random": "random_note", "random:read": "random_note",
    "wordcount": "word_count", "bases": "list_files (kinds=base)", "base:views": "read_base",
    "vault": "vault_info", "vaults": "list_vaults", "snippets": "themes_and_snippets",
    "snippets:enabled": "themes_and_snippets", "themes": "themes_and_snippets", "theme": "themes_and_snippets",
    "bookmarks": "read_app_config (bookmarks.json)", "hotkeys": "read_app_config (hotkeys.json)",
    "plugins": "community_plugins", "plugins:enabled": "community_plugins",
}


def main() -> None:
    cat = catalog()
    lines = [
        "# Obsidian CLI coverage",
        "",
        f"Generated by `scripts/gen_cli_coverage.py` from the official CLI page "
        f"([source]({cat['source']}), commit `{cat['source_commit'][:7]}`, {cat['source_date']}).",
        f"Requires the Obsidian {cat['minimum_installer']}+ installer with the CLI enabled and the app running.",
        "",
        "Every command is reachable through `cli_run` (validated against this catalog). "
        "\"Typed tool\" is a friendlier wrapper; \"Offline equivalent\" works from files with Obsidian closed.",
        "",
        "| Section | Command | Risk / permission | Confirm | Typed tool | Offline equivalent |",
        "|---|---|---|---|---|---|",
    ]
    for c in cat["commands"]:
        risk = CLI_RISK[c["name"]]
        lines.append(f"| {c['section']} | `{c['name']}` | {risk.value} | {'yes' if risk in CONFIRM_RISKS else ''} | "
                     f"{TYPED.get(c['name'], '')} | {LOCAL.get(c['name'], '')} |")
    lines += ["", f"Total documented commands: {len(cat['commands'])}.", ""]
    out = Path(__file__).resolve().parents[1] / "docs" / "CLI_COVERAGE.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
